### ISSUE TITLE
Question: Custom Actions for Simple Vacuum Card

### ISSUE THREAD

**Issue by danielzrob** [romedtino/simple-wyze-vac#10]
Has anyone else had issues adding the custom actions to the little toolbar in the custom card? 

There is no reported bugs for it on Vacuum_Card and I just wanted to see if anyone using the wyze implementation was having issues.

Love this integration btw thank you!

**Comment by romedtino** [comment]
Oh they changed the way you write custom actions not too long ago. Mine looks like this now for example

```
type: custom:vacuum-card
entity: vacuum.theovac
image: default
show_toolbar: true
show_status: true
show_name: true
compact_view: false
shortcuts:
  - name: Clean living room
    service: script.vacuum_room_clean
    icon: mdi:sofa
    service_data:
      rooms:
        - Living Room
  - name: Update
    service: script.vacuum_update_state
    icon: mdi:update
view_layout:
  position: sidebar
```
