### ISSUE TITLE
[QUESTION] Anyone have a working Xiomi lovelace config with room selection?

### ISSUE THREAD

**Issue by SpartanTech** [romedtino/simple-wyze-vac#64]
Simple question hopefully I can close after.

Does anyone have a working xiomi lovelace card config they can paste here for me that works with rooms? Im looking at the wiki on their github and Im failing to make any kind of room show up on the lovelace card. I have 8 rooms defined (on wyze app), they show up on home assistant okay, but getting the xiomi card to showup with rooms i cant get working. 

Would anyone mind pasting their config?

`type: custom:xiaomi-vacuum-map-card
title: Vacuum
entity: vacuum.romo_vacuum
vacuum_platform: romedtino/simple-wyze-vac
map_source:
  camera: camera.romo_vacuum_camera
map_locked: true
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: Kitchen
        outline: [[301, 812, 753, 1624]]
        label:
          text: "Kitchen"
          x: 400
          y: 850
          offset_y: 35
        icon:
          name: "mdi:bed"
          x: 400
          y: 750
      - id: Bathroom
        outline: [[342, 2258, 451, 2570]]
        label:
          text: "Bathroom"
          x: 322
          y: 2264
          offset_y: 35
        icon:
          name: "mdi:shower"
          x: 322
          y: 2264`

**Comment by romedtino** [comment]
Neat, didn't know this card existed. I've mostly been using denysdovhan's `Vacuum Card`. I might take a poke and see if I can set mine up and I'll let you know

**Comment by romedtino** [comment]
Follow up- Seems to work pretty well
Here's a screenshot-
![image](https://github.com/romedtino/simple-wyze-vac/assets/18567128/b06aa45e-4099-4666-9b30-41125c7a82ea)

Here's my yaml
```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.theovac
vacuum_platform: romedtino/simple-wyze-vac
map_source:
  camera: camera.theovac_camera
map_locked: false
title: TheoVac
two_finger_pan: false
map_modes:
  - template: vacuum_clean_segment
    predefined_selections:
      - id: Bedroom
        outline:
          - - 360
            - 500
          - - 360
            - 950
          - - 950
            - 950
          - - 950
            - 500
        label:
          text: Bedroom
          x: 680
          'y': 690
          offset_y: 35
        icon:
          name: mdi:bed
          x: 680
          'y': 690
```
I'm thinking your outline is missing a few fields, it should be this for a rectangle
```
[ [x1, y1], [x1, y2], [x2, y2], [x2, y1] ]
```
and the coordinates become
```
[x1, y1]                          [x1, y2]


[x2, y1]                          [x2, y2]
```
Good luck and good find! :D I might switch to this card now too
