### ISSUE TITLE
Support for multiple floors?

### ISSUE THREAD

**Issue by boberthepker** [romedtino/simple-wyze-vac#70]
Hello,

Great work on this BTW! 

Could someone point me in the right direction of determining if adding support for multiple floors is possible? The Wyze app has it, but I'm not sure what API limitations this integration has. Right now, my workaround is to open the Wyze app, switch floors, and then use Home Assistant again.

Thanks!

**Comment by romedtino** [comment]
Hey, the capability is actually there (added from this PR - https://github.com/romedtino/simple-wyze-vac/pull/54 thanks to kevinyc), probably something that should be added to the README but you can add a service call 

```
service: vacuum.send_command
data:
  command: set_current_map
  params:
    map: YOUR MAP NAME HERE
target:
  entity_id: vacuum.YOUR_VACUUM_NAME_HERE
```
![image](https://github.com/romedtino/simple-wyze-vac/assets/18567128/c3e76825-3556-431a-af74-57cbbadc46c9)

Like so, to change maps
