### ISSUE TITLE
Polling Doesn't Update

### ISSUE THREAD

**Issue by teek541** [romedtino/simple-wyze-vac#84]
I've set polling to 10sec as well as 1min.  I've restarted the integration after the changes (I noticed it wasn't updating at 1min from my initial configuration a few weeks ago).  The integration doesn't update.  If I send a command it does, but if I'm in the app, and pause the vacuum, or if it stops and gets hung up, the state doesn't update in the integration.  I have to send the update command in the integration for it to poll new statuses.  Enabling debug didn't reveal anything in the logs.

**Comment by danielzrob** [comment]
Yeah me too on this one. Looks like rooms won't select from HA either anymore. 

I don't know that this is being maintained anymore. Wyze keeps making it a moving target :(

**Comment by teek541** [comment]
I am using the switches and just doing the auto clean function and it seems to work.

**Comment by romedtino** [comment]
Yea, polling in code is currently disable so the README is currently misleading that enabling polling through config is working. 

As a workaround for now, you can create an action that calls the `update` command for the the wyze vac e.g.

```
description: "Update my vaccum every minute"
mode: single
trigger:
  - platform: time_pattern
    minutes: "1"
condition: []
action:
  - action: vacuum.send_command
    metadata: {}
    data:
      command: update
    target:
      entity_id: vacuum.my_vac

```

Just keep in mind the rate limits. I've seen people change the polling rate depending on if it's actually running and that might help to avoid rate limits
